title: "DTun: Data Tunnel"
author: pezy
email: urbancpz@gmail.com

timezone: Asia/Shanghai
date_format: "%Y-%m-%d"

permalink: /:year/:month/:day/:title/
excerpt_separator: <!--more-->

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

sass:
  style: compressed
