title: pezy blog      
description: a link blog
author: pezy
email: urbancpz@gmail.com

timezone: Asia/Shanghai     
date_format: "%Y-%m-%d"     

permalink: /:year/:month/:day/:title/  
excerpt_separator: <!--more-->         

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
